name: Citation Check

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  check-citation:
    name: Check CITATION.cff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate CITATION.cff
        uses: citation-file-format/cffconvert-github-action@2.0.0
        with:
          args: "--validate"
